title: Bughht's Blog
description: My Personal Blog
author: Haotian Hong 
github: https://github.com/bughht
about: I'm Haotian from Shanghai University, School of Communication & Information Engineering, major in BME. My research interests include Brain-Computer Interface, Medical Image Processing, VR/AR etc.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-qq
      link: "tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=1725607268&website=www.oicqzone.com"
    - icon: fa-wechat
      link: "./Personal_Information/wechat"
    - icon: fa-github
      link: "https://github.com/bughht/"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://bughht.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown:  kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
